spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: juggler.stackroute@gmail.com
    password: juggler123
    port: "587"
    protocol: smtp
    test-connection: "false"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
server:
  port: "8051"
