spring:

 datasource:
   url: jdbc:mysql://172.23.239.108:3306/juggler_db?useSSL=false
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: create
   database-platform: org.hibernate.dialect.MySQL5Dialect
   generate-ddl: "true"
   show-sql: "true"
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://172.23.239.116:9090/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
