spring:
 data:
   neo4j:
     username: neo4j
     password: baby@8686
 application:
   name: recommendation-ms
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://172.23.239.116:9090/eureka/
