spring:
 data:
   neo4j:
     username: neo4j
     password: baby@8686
     uri: bolt://localhost

 application:
   name: recommendation-ms
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://localhost:9090/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
