
spring:
 data:
  mongodb:
   database: event
   host: localhost
   port: "27017"
   uri: mongodb://172.23.239.108/event
management:
 endpoints:
  web:
   exposure:
    include: "*"
eureka:
 client:
   service-url:
     defaultZone: http://172.23.239.116:9090/eureka
   register-with-eureka: "true"
   fetch-registry: "true"

