spring:
 application:
   name: screening

 data:
 
   mongodb:
     database: movie-schedule
     host: 10.20.1.216
     port: "27017"
     uri: mongodb://172.23.239.108/movie-schedule
     username: ""
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://172.23.239.116:9090/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
