spring:
 application:
   name: movie-search
 cloud:
   config:
     uri: http://localhost:8891
 data:
   mongodb:
     database: moviedb
     host: localhost
     port: "27017"
     uri: mongodb://10.20.1.216/moviedb
     username: ""

eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://localhost:9090/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
