spring:
 application:
   name: theatre
 data:
   mongodb:
     database: theatre
     host: 172.23.239.108
     port: "27017"
     uri: mongodb://172.23.239.108/theatre
     username: ""
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   service-url:
     defaultZone: http://172.23.239.116:9090/eureka
management:
 endpoints:
  web:
   exposure:
    include: "*"
