
spring:
  data:
    mongodb:
      database: userdb
      host: localhost
      port: "27017"
      uri: mongodb://172.23.239.108/userdb
      username: ""
  application:
    name: UserProfile
  cloud:
    config:
      uri: http://localhost:8891
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://172.23.239.116:9090/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"

