
spring:
  data:
    mongodb:
      database: userdb
      host: 172.23.239.108
      port: "27017"
      uri: mongodb://localhost/userdb
      username: ""
  application:
    name: UserProfile
  cloud:
    config:
      uri: http://localhost:9084
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://localhost:9083/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"

